Description of test_compl_elec_mdl
Home > eidors > tests > test_compl_elec_mdl.m
test_compl_elec_mdl
PURPOSE
Test formation of complete electrode model
SYNOPSIS
This is a script file.
DESCRIPTION
 Test formation of complete electrode model
CROSS-REFERENCE INFORMATION
This function calls:
mk_common_model MK_COMMON_MODEL: make common EIT models
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
This function is called by:
SOURCE CODE
% Test formation of complete electrode model
imdl= mk_common_model('a2c2',8);
fmdl= imdl.fwd_model;
for i=1:8;
   fmdl.electrode(i).nodes = fmdl.electrode(i).nodes + [0,1];
end
img= calc_jacobian_bkgnd(imdl);
system_mat_1st_order(fmdl,img);
disp('success'); % if we have no errors