Description of test_colour_direction
Home > eidors > tests > test_colour_direction.m
test_colour_direction
PURPOSE
Test colour mapping
SYNOPSIS
This is a script file.
DESCRIPTION
 Test colour mapping
 $Id: test_colour_direction.m 1535 2008-07-26 15:36:27Z aadler $
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
calc_slices calc_slices (img, levels, clim) show slices at levels of an
show_fem SHOW_FEM: show the EIDORS3D finite element model
mk_common_model MK_COMMON_MODEL: make common EIT models
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
inv_solve INV_SOLVE: calculate imag from an inv_model and data
This function is called by:
SOURCE CODE
% Test colour mapping
% $Id: test_colour_direction.m 1535 2008-07-26 15:36:27Z aadler $
% 2D Test
imdl= mk_common_model('b2c',16);
s_img= eidors_obj('image','');
s_img.fwd_model= imdl.fwd_model;
s_img.elem_data= ones(size(s_img.fwd_model.elems,1),1);
v_homg = fwd_solve(s_img);
s_img.elem_data(1)= 1.1;
v_targ = fwd_solve(s_img);
imgr1= inv_solve(imdl,v_homg,v_targ);
slice1= calc_slices(imgr1);
subplot(121)
show_fem(imgr1);
disp('image should be red');
% 3D Test
imdl= mk_common_model('n3r2',[16 2]);
s_img= eidors_obj('image','');
s_img.fwd_model= imdl.fwd_model;
s_img.elem_data= ones(size(s_img.fwd_model.elems,1),1);
v_homg = fwd_solve(s_img);
s_img.elem_data(1)= 1.1;
v_targ = fwd_solve(s_img);
imgr2= inv_solve(imdl,v_homg,v_targ);
subplot(122)
show_fem(imgr2);
disp('image should be red');