Description of find_boundary
Home > eidors > solvers > forward > find_boundary.m
find_boundary
PURPOSE
[srf, idx] = find_boundary(simp);
SYNOPSIS
function [srf, idx] = find_boundary(simp);
DESCRIPTION
 [srf, idx] = find_boundary(simp);
Caclulates the boundary faces of a given 3D volume.
Usefull in electrode assignment.
srf  =  array of elements on each boundary simplex
        boundary simplices are of 1 lower dimention than simp
idx  =  index of simplex to which each boundary belongs
simp = The simplices matrix
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mk_common_model MK_COMMON_MODEL: make common EIT models
find_boundary [srf, idx] = find_boundary(simp);
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
eidors_model_params mdl = eidors_model_params(mdl);
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
set_fwd_model SET_FWD_MODEL: create EIDORS v3 fwd_model from v2 parameters
demo_real [inhomg_img, demo_img] = demo_real;
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts, any_cuts)
show_fem SHOW_FEM: show the EIDORS3D finite element model
dm_2d_pt_elecs DM_2D_PT_ELECS: Create circle mesh (or radius 1) refined
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
gmsh_mk_fwd_model GMSH_MK_FWD_MODEL: create a fwd_model object from a Gmsh file
join_models JOIN_MODELS: Join two fmdl structures to create one
mdl2d_from3d mdl2d_from3d: Create 2D mdl from z=0 plane of 3d model
ng_mk_2d_model NG_MG_2D_MODELS create a 2D mesh with Netgen via the in2d interface
ng_mk_extruded_model NG_MAKE_EXTRUDED_MODEL: create extruded models using netgen
stl_read STL_READ Read in an stl file and output an EIDORS model struct
GREIT3D_distribution GREIT3D_distribution: create target distributions for 3D GREIT
fix_model FIX_MODEL: Add useful fields to a model
fwd_model_from_v2 CREATE EIDORS v3 fwd_model from the v2 variables
merge_meshes MERGE_MESHES - merges two meshes based on common nodes
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_fmdl_from_nodes MK_FMDL_FROM_NODES: create fmdl from nodes
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_hollow_electrode MK_HOLLOW_ELECTRODE: remove nodes with indicated electrdoes
mk_pixel_slice MK_PIXEL_SLICE create a pixel model to reconstruct on
solve_RM_2Dslice SOLVE_RM_2DSLICE: cut slices out of a 3D model
find_boundary [srf, idx] = find_boundary(simp);
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
test_3d_resistor Create 3D model of a Rectangular resistor
SUBFUNCTIONS
function [srf,idx]= find_2or3d_boundary(simp,dim);
function [srf,idx]= find_1d_boundary(simp);
function x = isunique(a);
function do_unit_test
function bdy= sort_boundary(bdy)
SOURCE CODE
function [srf, idx] = find_boundary(simp);
% [srf, idx] = find_boundary(simp);
%
%Caclulates the boundary faces of a given 3D volume.
%Usefull in electrode assignment.
%
%srf  =  array of elements on each boundary simplex
%        boundary simplices are of 1 lower dimention than simp
%idx  =  index of simplex to which each boundary belongs
%simp = The simplices matrix
% $Id: find_boundary.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(simp) && strcmp(simp,'UNIT_TEST'); do_unit_test; return; end
if isstruct(simp) && strcmp(simp.type,'fwd_model'); simp= simp.elems; end
wew = size(simp,2) - 1;
if wew==3 || wew==2
   [srf,idx]= find_2or3d_boundary(simp,wew);
elseif wew == 1
   [srf,idx]= find_1d_boundary(simp);
else
   eidors_msg('find_boundary: WARNING: not 1D, 2D or 3D simplices',1);
   srf=[]; return;
end
% sort surfaces. If there is more than one, its not on the boundary
function [srf,idx]= find_2or3d_boundary(simp,dim);
   if size(simp,1) < 4e9 % max of uint32
      % convert to integer to make sort faster
      simp = uint32( simp );
   end
   localface = nchoosek(1:dim+1,dim);
   srf_local= simp(:,localface');
   srf_local= reshape( srf_local', dim, []); % D x 3E
   srf_local= sort(srf_local)'; % Sort each row
   [sort_srl,sort_idx] = sortrows( srf_local );
   % Fine the ones that are the same
   first_ones =  sort_srl(1:end-1,:);
   next_ones  =  sort_srl(2:end,:);
   same_srl = find( all( first_ones == next_ones, 2) );
   % Assume they're all different. then find the same ones
   diff_srl = logical(ones(size(srf_local,1),1));
   diff_srl(same_srl) = 0;
   diff_srl(same_srl+1) = 0;
   srf= sort_srl( diff_srl,: );
   idx= sort_idx( diff_srl);
   idx= ceil(idx/(dim+1));
function [srf,idx]= find_1d_boundary(simp);
   if size(simp,1) < 4e9 % max of uint32
      % convert to integer to make sort faster
      simp = uint32( simp );
   end
   % we expect two nodes as a result
   idx = find(isunique(simp(:)) == 1);
   srf = simp(idx);
   idx = rem(idx-1,size(simp,1))+1;
function x = isunique(a);
   u=unique(a);
   n=histc(a,u);
   x=ismember(a,u(n==1));
function do_unit_test
%2D Test:
mdl = mk_common_model('c2c',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
unit_test_cmp('2D test', bdy, bdyc);
%3D Test:
mdl = mk_common_model('n3r2',[16,2]);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
unit_test_cmp('3D test n3r2', bdy,bdyc);
%3D Test:
mdl = mk_common_model('a3cr',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
unit_test_cmp('3D test a3c2', bdy, bdyc);
%3D Test:
mdl = mk_common_model('b3cr',16);
bdy = find_boundary(mdl.fwd_model.elems);
bdy = sort_boundary(bdy);
bdyc= sort_boundary(mdl.fwd_model.boundary);
unit_test_cmp('3D test b3c2', bdy, bdyc);
simp = [  10 190; ...
         182 183; ...
         183 184; ...
         184 185; ...
          11 182; ...
         185 186; ...
         187 186; ...
         187 188; ...
         188 189; ...
         189 190];
[bdy, idx] = find_boundary(simp);
unit_test_cmp('1D bdy', bdy,[10;11]);
unit_test_cmp('1D bdy', idx,[1;5]);
function bdy= sort_boundary(bdy)
   bdy = sort(bdy,2);
   bdy = sortrows(bdy);