Description of eidors_debug
Home > eidors > tools > eidors_debug.m
eidors_debug
PURPOSE
EIDORS_DEBUG Global managment of debug flags
SYNOPSIS
function out = eidors_debug(command, fstr)
DESCRIPTION
EIDORS_DEBUG Global managment of debug flags
 eidors_debug('on','function')
     switches ON the debug flag for string constant 'function'
 eidors_debug('off','function')
     switches OFF the debug flag for string constant 'function'
 eidors_debug('off','all')
     switches OFF the debug flag for all functions
 eidors_debug('query','function')
     returns the current state of the debug flag for 'function'
 Note that 'function' can be any string constant (other than 'all'), but
 it is recommended to be an actual eidors function name. To enable
 debugging on selected parts of the code, follow this convention:
    eidors_function:part1
    eidors_function:subfunction
    eidors_function:subfunction:part1
 Example use in code (my_function.m):
 if eidors_debug('query','my_function')
     disp(val)
 end
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_debug EIDORS_DEBUG Global managment of debug flags
This function is called by:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
system_cmd SYSTEM_CMD: issue system commands, and try to compensate for
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
eidors_debug EIDORS_DEBUG Global managment of debug flags
progress_msg PROGRESS_MSG Progress messages and timing.
SUBFUNCTIONS
function test
function do_unit_test
SOURCE CODE
function out = eidors_debug(command, fstr)
%EIDORS_DEBUG Global managment of debug flags
% eidors_debug('on','function')
%     switches ON the debug flag for string constant 'function'
% eidors_debug('off','function')
%     switches OFF the debug flag for string constant 'function'
% eidors_debug('off','all')
%     switches OFF the debug flag for all functions
% eidors_debug('query','function')
%     returns the current state of the debug flag for 'function'
%
% Note that 'function' can be any string constant (other than 'all'), but
% it is recommended to be an actual eidors function name. To enable
% debugging on selected parts of the code, follow this convention:
%    eidors_function:part1
%    eidors_function:subfunction
%    eidors_function:subfunction:part1
%
% Example use in code (my_function.m):
% if eidors_debug('query','my_function')
%     disp(val)
% end
% (C) 2013 Bartlomiej Grychtol.
% License: GPL version 2 or 3
% $Id: eidors_debug.m 4924 2015-05-07 23:09:59Z aadler $
if ischar(command) && strcmp(command, 'UNIT_TEST'), do_unit_test;return; end
global eidors_objects;
if ~isfield(eidors_objects, 'debug_enabled_on')
   eidors_objects.debug_enabled_on = {};
end
switch command
   case 'on'
      if ~eidors_debug('query',fstr);
         eidors_objects.debug_enabled_on{end+1} = fstr;
      end
   case 'off'
      if nargin==1 || strcmp(fstr, 'all')
         eidors_objects.debug_enabled_on = {};
      else
         idx = strcmp(eidors_objects.debug_enabled_on, fstr);
         eidors_objects.debug_enabled_on(idx) = [];
      end
   case 'query'
      idx = strcmp(eidors_objects.debug_enabled_on, fstr);
      out = any(idx);
   otherwise
      error('EIDORS:WrongInput',['First input to eidors_debug must be ', ...
         '''on'',''off'' or ''query''.']);
end
function test
if eidors_debug('query','eidors_debug_test1')
   eidors_msg('TEST1',2);
end
if eidors_debug('query','eidors_debug_test2')
   eidors_msg('TEST2',2);
end
function do_unit_test
eidors_debug on eidors_debug_test1
eidors_debug on eidors_debug_test2
test
eidors_debug off eidors_debug_test1
test
eidors_debug off all
test
fprintf('expected output:\n[%s]\n[%s]\n[%s]\n',  ...
  'TEST1', ...
  'TEST2', ...
  'TEST2');