Description of eidors_msg
Home > eidors > eidors_msg.m
eidors_msg
PURPOSE
EIDORS_MSG eidors progress and status messages
SYNOPSIS
function log_level= eidors_msg(message, varargin)
DESCRIPTION
EIDORS_MSG eidors progress and status messages
  EIDORS_MSG(STR, LVL) prints 'EIDORS:[ STR ]' if current log_level <= LVL
     If the message starts with '@@@' then the characters are replaced
     with the calling function's name. Default LVL = 2.
  EIDORS_MSG(STR, LVL, ...) uses STR as format string for fprintf passing
     to it any additional arguments.
  LVL = EIDORS_MSG('log_level') returns the current log_level
  EIDORS_MSG('log_level', LVL) sets the log_level for all of EIDORS
  or EIDORS_MSG  log_level  LVL
  EIDORS_MSG('log_level', LVL, FNAME) sets a custom log_level for m-file
     FNAME (provide without extension)
  EIDORS_MSG('log_level','reset', FNAME) resets the log_level for m-file
     FNAME to the default level
  EIDORS_MSG('log_level','reset')
  EIDORS_MSG('log_level','reset','all') resets all custom log-level
     settings to default
  Meanings of levels:
     0 => keep quiet (no messages should be level=0)
     1 => important messages
     2 => most messages
     3 => detailed information%
     4 => very detailed information
  Examples:
  eidors_msg('mission accomplished; time to relax', 1) prints
     >> EIDORS:[ mission accomplished; time to relax ]'
       if log_level <=1
  less important messages have higher levels
  eidors_msg('did %d of %s at %f', 2, 'stuff', sqrt(2), 1)
     >> EIDORS:[ did 2 of stuff at 1.414214 ]
  eidors_msg('@@');
     >> EIDORS:[eidors_msg]
  eidors_msg('@@@');
     >> EIDORS:[eidors_msg/do_unit_test]
  eidors_msg('@@@ a message',1);
     >> EIDORS:[eidors_msg/do_unit_test: a message]
  See also EIDORS_DEBUG, EIDORS_CACHE.
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
This function is called by:
eval_GREIT_fig_merit EVAL_GREIT_FIG_MERIT: calculate GREIT figures of merit for images
frame_timing_correct FRAME_TIMING_CORRECT: Corrects serially collected *.get data so that each
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
edge_refined_elem_mapper EDGE_REFINED_ELEM_MAPPER: map elements from coarse to dense model
edge_refined_node_mapper EDGE_REFINED_NODE_MAPPER:
forward_solver [V] = forward_solver(E,I,tol,pp,V);
image_levels IMAGE_LEVELS(img, levels, clim) show slices at levels of an image
np_calc_image_prior NP_CALC_IMAGE_PRIOR calculate image prior
np_calc_system_mat NP_CALC_SYSTEM_MAT: s_mat= np_calc_system_mat(fwd_model, img)
np_fwd_parameters NP_FWD_PARAMETERS: data= np_fwd_solve(fwd_model)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
eidors_startup Script to start EIDORS
demo_real [inhomg_img, demo_img] = demo_real;
moving_tank_objs MOVING_TANK_OBJS: create movies of objects moving in tanks
resistor_model DEMO to show really simple application of EIDORS framework
calc_colours [colours,scl_data]= calc_colours(img, set_value, do_colourbar)
calc_slices calc_slices (img, levels, clim) show slices at levels of an
common_colourbar COMMON_COLOURBAR make a joint colourbar for several subplots
print_convert PRINT_CONVERT: print figures with anti-aliasing and trim them
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
show_slices out_img = show_slices (img, levels) show slices at levels of an
eidors_readdata EIDORS readdata - read data files from various EIT equipment
crop_model CROP_MODEL: Crop away parts of a fem model
dm_2d_circ_pt_elecs DM_2D_CIRC_PT_ELECS: Create circle mesh (or radius 1) refined with electrodes
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
fourier_fit FOURIER_FIT: use fourier series to interpolate onto a boundary
ng_mk_cyl_models NG_MAKE_CYL_MODELS: create cylindrical models using netgen
ng_mk_gen_models NG_MK_GEN_MODELS: create generic models using netgen
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
ng_read_mesh [srf,vtx,fc,bc,simp,edg,mat_ind] = ng_read_mesh(filename)
ng_mk_common_model NG_MK_COMMON_MODEL: utility to create common models
data_mapper DATA_MAPPER maps img.params data to elem or node data
find_edge2edge_intersections FIND_EDGE2EDGE_INTERSECTIONS intersections between edges of two models
fix_model FIX_MODEL: Add useful fields to a model
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_analytic_c2f MK_ANALYTIC_C2F: create a mapping matrix from coarse to fine FEM
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_library_model MK_LIBRARY_MODEL - FEM models based on library shapes
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
select_imdl SELECT_IMDL: select pre-packaged inverse model features
shape_library SHAPE_LIBRARY Common shapes for models
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 3D
uniquetol C = uniquetol(A,TOL): unique values in A using tolerance TOL.
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
eit_spice function spice = eit_spice(img, [name])
find_boundary [srf, idx] = find_boundary(simp);
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
inv_solve INV_SOLVE: calculate imag from an inv_model and data
GREIT_desired_img_sigmoid GREIT_DESIRED_IMG_SIGMOID sigmoid-decay desired image function for GREIT
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
calc_solution_error CALC_SOLUTION_ERROR Calculate residuals for a solution
choose_image_SNR % CHOOSE_IMAGE_SNR: choose hyperparameter based on image SNR calculation
choose_noise_figure CHOOSE_NOISE_FIGURE: choose hyperparameter based on NF calculation
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
mk_GN_model MK_GN_MODEL: make EIDORS inverse models using the GREIT approach
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test Perform tests based on the demo_real function
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
tutorials_test TUTORIAL_TEST: Run all tutorials
eidors_cache EIDORS_CACHE Control eidors caching
eidors_debug EIDORS_DEBUG Global managment of debug flags
progress_msg PROGRESS_MSG Progress messages and timing.
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
SUBFUNCTIONS
function log_level = process_log_level(varargin)
function [file fun] = get_caller
function [log_level] = get_levels
function do_unit_test
function extra_caller
SOURCE CODE
function log_level= eidors_msg(message, varargin)
%EIDORS_MSG eidors progress and status messages
%
%  EIDORS_MSG(STR, LVL) prints 'EIDORS:[ STR ]' if current log_level <= LVL
%     If the message starts with '@@@' then the characters are replaced
%     with the calling function's name. Default LVL = 2.
%
%  EIDORS_MSG(STR, LVL, ...) uses STR as format string for fprintf passing
%     to it any additional arguments.
%
%  LVL = EIDORS_MSG('log_level') returns the current log_level
%
%  EIDORS_MSG('log_level', LVL) sets the log_level for all of EIDORS
%  or EIDORS_MSG  log_level  LVL
%
%  EIDORS_MSG('log_level', LVL, FNAME) sets a custom log_level for m-file
%     FNAME (provide without extension)
%
%  EIDORS_MSG('log_level','reset', FNAME) resets the log_level for m-file
%     FNAME to the default level
%
%  EIDORS_MSG('log_level','reset')
%  EIDORS_MSG('log_level','reset','all') resets all custom log-level
%     settings to default
%
%  Meanings of levels:
%     0 => keep quiet (no messages should be level=0)
%     1 => important messages
%     2 => most messages
%     3 => detailed information%
%     4 => very detailed information
%
%  Examples:
%  eidors_msg('mission accomplished; time to relax', 1) prints
%     >> EIDORS:[ mission accomplished; time to relax ]'
%       if log_level <=1
%  less important messages have higher levels
%
%  eidors_msg('did %d of %s at %f', 2, 'stuff', sqrt(2), 1)
%     >> EIDORS:[ did 2 of stuff at 1.414214 ]
%
%  eidors_msg('@@');
%     >> EIDORS:[eidors_msg]
%
%  eidors_msg('@@@');
%     >> EIDORS:[eidors_msg/do_unit_test]
%
%  eidors_msg('@@@ a message',1);
%     >> EIDORS:[eidors_msg/do_unit_test: a message]
%
%  See also EIDORS_DEBUG, EIDORS_CACHE.
% (C) 2005-2014 Andy Adler and Bartlomiej Grychtol
% License: GPL version 2 or version 3
% $Id: eidors_msg.m 5111 2015-06-14 12:55:54Z aadler $
if ischar(message) && strcmp(message,'UNIT_TEST'); do_unit_test; return; end
if ischar(message) && strcmp(message, 'log_level')
   log_level = process_log_level(varargin{:});
   return;
end
if nargin==1
   args= {};
   level= 2;
else
   level= varargin{ nargin-1 };
   args= varargin( 1:nargin-2 );
end
[log_level] = get_levels;
if level > log_level
    return
end
for i= 1:length(args)
   if isa( args{i}, 'function_handle')
      args{i} = func2str(args{i});
   end
end
% It makes sense to print to stderr (fid=2), but matlab>7 prints this in red
ver= eidors_obj('interpreter_version');
if ver.ver>=7; fid= 1;
else ;         fid= 2; end
%try, lms= eidors_objects.last_message_size;
%  if lms>0; fprintf(fid,'%c', 8*ones(lms,1)); end
%end
% deal with variables
if ~ischar(message)
   var = inputname(1);
   message = [var ' = ' num2str(message)];
end
% Need to do twice to interpret text in message
% message= sprintf(message, args{:});
if length(message)>1 % single characters are just for progress
   if length(message)>=2 && strcmp(message(1:2),'@@');
      if length(message)==2; msg_extra = '';
      else                   msg_extra = [':', message(3:end)];
      end
      [file fun] = get_caller();
      dbs = dbstack;
      if length(message) > 2 && message(3) == '@'
          if length(message) == 3
              msg_extra = '';
          else
              msg_extra(2) = [];
          end
          message = sprintf('%s/%s%s', file, fun, msg_extra);
      else
          message = sprintf('%s%s', file , msg_extra);
      end
   end
   string= [sprintf('%c',' ' * ones(1,level-1)), ...
            'EIDORS:[',message,']\n'];
else
   string= message;
end
fprintf(fid, string, args{:});
if exist('OCTAVE_VERSION'); fflush(fid); end
eidors_objects.last_message_size= 0;
function log_level = process_log_level(varargin)
   global eidors_objects
   if isempty(varargin)
      % eidors_msg('log_level');
      log_level = eidors_objects.log_level;
      return
   end
   if ischar(varargin{1}) && ~isempty(str2num(varargin{1}))
      varargin{1} = str2num(varargin{1});
   end
   if isnumeric(varargin{1})
      log_level = eidors_objects.log_level;
      switch nargin
         case 1
            % eidors_msg('log_level', 2);
            eidors_objects.log_level = varargin{1};
         case 2
            % eidors_msg('log_level', 1, fname);
            caller = get_caller;
            custom = eidors_objects.log_level_custom;
            if isempty(custom), return, end
            idx = find(ismember(caller, custom.names), 1);
            if isempty(idx), idx = length(custom.levels) + 1; end
            eidors_objects.log_level_custom.names{idx} = caller;
            eidors_objects.log_level_custom.levels(idx) = varargin{1};
         otherwise
            error('Wrong number of inputs');
      end
   elseif ischar(varargin{1}) && strcmp(varargin{1}, 'reset')
      log_level = eidors_objects.log_level;
      switch nargin
         case 1
            % eidors_msg('log_level','reset');
            eidors_objects.log_level_custom.names = {};
            eidors_objects.log_level_custom.levels = [];
         case 2
            switch varargin{2}
               case 'all'
                  % eidors_msg('log_level','reset', 'all');
                  eidors_objects.log_level_custom.names = {};
                  eidors_objects.log_level_custom.levels = [];
               otherwise
                  caller = get_caller;
                  idx = find(ismember(caller, ...
                              eidors_objects.log_level_custom.names{1}), 1);
                  eidors_objects.log_level_custom.names(idx) = [];
                  eidors_objects.log_level_custom.levels(idx) = [];
            end
         otherwise
            error('Wrong number of inputs');
      end
   else
      error('Wrong input, consult help.');
   end
function [file fun] = get_caller
   dbs = dbstack;
   file = dbs(3).file;
   idx = find(file == '.', 1, 'last');
   if isempty(idx), idx = length(file)+1; end
   file = file(1:idx-1);
   fun =  dbs(3).name;
function [log_level] = get_levels
   global eidors_objects
   try
      custom = eidors_objects.log_level_custom;
   catch
      custom.names = {};
      custom.levels = [];
      eidors_objects.log_level_custom = custom;
   end
   if ~isempty(custom)
      % find caller file name
      file = get_caller;
      % check for custom flag
      idx = find(ismember(file, custom.names));
      if ~isempty(idx)
         log_level = custom.levels(idx);
         return
      end
   end
   try
      log_level= eidors_objects.log_level;
   catch
      log_level= 2; % default;
      eidors_objects.log_level= log_level;
   end
function do_unit_test
   ll= eidors_msg('log_level');
   eidors_msg('log_level',5);
   eidors_msg('l1',1); eidors_msg('l2',2); eidors_msg('l3',3); eidors_msg('l4',4);
   eidors_msg('log_level',1);
   eidors_msg('l1',1); eidors_msg('l2',2); eidors_msg('l3',3); eidors_msg('l4',4);
   eidors_msg('@@',1);
   eidors_msg('@@@',1);
   eidors_msg('@@ a message',1);
   eidors_msg('@@@ a message',1);
   eidors_msg('a @@ message',1);
   eidors_msg('a @@@ message',1);
   extra_caller;
   % test custom levels
   eidors_msg('log_level',2);
   eidors_msg('FAIL',3);
   eidors_msg('log_level',1, 'eidors_msg');
   eidors_msg('PASS',1);
   eidors_msg('FAIL',2);
   eidors_msg('log_level',3, 'eidors_msg');
   eidors_msg('PASS',3);
   eidors_msg('FAIL',4);
   eidors_msg('log_level','reset','eidors_msg');
   eidors_msg('PASS',2);
   eidors_msg('FAIL',3);
   % just for fun
   eidors_msg('log_level','reset');
   eidors_msg('log_level','reset','all');
   eidors_msg('log_level',ll);
function extra_caller
   eidors_msg('@@@ a message from extra_caller',1);
   eidors_msg('@@ a shorter message from extra caller',1);