Description of elem_dim
Home > eidors > models > elem_dim.m
elem_dim
PURPOSE
ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
SYNOPSIS
function num = elem_dim(mdl);
DESCRIPTION
 ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
  Note, elem_dim is not the same as the model dimention (can have 2D models in 3D space)
 num_dim = elem_dim( mdl );
    = 2 if 2D, 3 if 3D
CROSS-REFERENCE INFORMATION
This function calls:
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
aa_calc_system_mat AA_CALC_SYSTEM_MAT: SS= aa_calc_system_mat(fwd_model, img)
calc_mesh_quality CALC_MESH_QUALITY Various measures of mesh quality.
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
fix_model FIX_MODEL: Add useful fields to a model
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
linear_reorder [fwd_model] = linear_reorder(fwd_model,ccw)
mk_analytic_c2f MK_ANALYTIC_C2F: create a mapping matrix from coarse to fine FEM
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
prior_gaussian_HPF PRIOR_GAUSSIAN_HPF calculate image prior
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = elem_dim(mdl);
% ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
%  Note, elem_dim is not the same as the model dimention (can have 2D models in 3D space)
% num_dim = elem_dim(mdl);
%    = 2 if 2D, 3 if 3D
% $Id: elem_dim.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if ~isfield(mdl,'type') && isfield(mdl,'elems') % Set default for this case
   mdl.type = 'fwd_model';
end
switch mdl.type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.elems,2)-1;
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = elem_dim( mdl );
   unit_test_cmp('test1', ne, 2);
   mdl = mk_common_model('n3r2',[16,2]);
   ne = elem_dim( mk_image( mdl ));
   unit_test_cmp('test2', ne, 3);