Description of elem_select
Home > eidors > models > elem_select.m
elem_select
PURPOSE
ELEM_SELECT: select element fractions inside a function
SYNOPSIS
function memb_frac = elem_select(fmdl, select_fcn)
DESCRIPTION
 ELEM_SELECT: select element fractions inside a function
   memb_frac = elem_select( fmdl, select_fcn )
  memb_frac = fraction of each element within the fcn
  fmdl =      fwd_model structure
  select_fcn = function to describe membership,
              can also be a cell array of functions, but all must accept
              parameters x, y, and z. ELEM_SELECT then finds elements that
              satisfy ALL the functions at once
              finally, select_fcn can be a string which will then
                be turned into a function via inline(str,'x','y','z')
 OR
 select_fcn = string accepting named variables x,y,z.
 parameters
   fwd_model.elem_select.interp_no  - interpolation density
 Example:
   img = mk_image(mk_common_model('b2d1c',8));
   select_fcn = inline('(x-0.2).^2+(y-0.5).^2<0.2^2','x','y','z');
   memb_frac = elem_select( img.fwd_model, select_fcn)
   img.elem_data = 1 + memb_frac*0.1;
   show_fem(img);
 Example
   img = mk_image(mk_common_model('b2d1c',8));
   select_fcn = '(x-0.2).^2+(y-0.5).^2<0.2^2';
   memb_frac = elem_select( img.fwd_model, select_fcn)
   img.elem_data = 1 + memb_frac*0.1;
   show_fem(img);
 See Also:
   mk_c2f_circ_mapping
CROSS-REFERENCE INFORMATION
This function calls:
elem_select ELEM_SELECT: select element fractions inside a function
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mk_common_model MK_COMMON_MODEL: make common EIT models
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
elem_select ELEM_SELECT: select element fractions inside a function
mk_hollow_electrode MK_HOLLOW_ELECTRODE: remove nodes with indicated electrdoes
mk_lung_image MK_LUNG_IMAGE create an image with lung and heart contrasts from a model
test_GREIT_model
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
SUBFUNCTIONS
function do_unit_test;
SOURCE CODE
function memb_frac = elem_select(fmdl, select_fcn)
% ELEM_SELECT: select element fractions inside a function
%   memb_frac = elem_select(fmdl, select_fcn)
%
%  memb_frac = fraction of each element within the fcn
%  fmdl =      fwd_model structure
%  select_fcn = function to describe membership,
%              can also be a cell array of functions, but all must accept
%              parameters x, y, and z. ELEM_SELECT then finds elements that
%              satisfy ALL the functions at once
%              finally, select_fcn can be a string which will then
%                be turned into a function via inline(str,'x','y','z')
% OR
% select_fcn = string accepting named variables x,y,z.
%
% parameters
%   fwd_model.elem_select.interp_no  - interpolation density
%
% Example:
%   img = mk_image(mk_common_model('b2d1c',8));
%   select_fcn = inline('(x-0.2).^2+(y-0.5).^2<0.2^2','x','y','z');
%   memb_frac = elem_select(img.fwd_model, select_fcn)
%   img.elem_data = 1 + memb_frac*0.1;
%   show_fem(img);
%
% Example
%   img = mk_image(mk_common_model('b2d1c',8));
%   select_fcn = '(x-0.2).^2+(y-0.5).^2<0.2^2';
%   memb_frac = elem_select(img.fwd_model, select_fcn)
%   img.elem_data = 1 + memb_frac*0.1;
%   show_fem(img);
%
% See Also:
%   mk_c2f_circ_mapping
if ischar(fmdl) && strcmp(fmdl,'UNIT_TEST'); do_unit_test; return; end
% 4 for 2D, 3 for 3D
dims = size(fmdl.nodes,2);
interp_no = 6 - dims;
try
   interp_no = fmdl.elem_select.interp_no;
end
pts = interp_mesh(fmdl, interp_no);
x = squeeze(pts(:,1,:));
y = squeeze(pts(:,2,:));
if dims ==2;
  z = 0*x;
else
  z = squeeze(pts(:,3,:));
end
if ischar(select_fcn)
%  we have a string, create a function
    select_fcn = inline(select_fcn, 'x','y','z');
    memb_frac = mean( feval(select_fcn,x,y,z), 2);
elseif ~iscell(select_fcn)
    % the normal case
    memb_frac = mean( feval(select_fcn,x,y,z), 2);
else
    % many functions case
    memb_val = ones(size(x));
    for i = 1:numel(select_fcn)
        memb_val = memb_val .* feval(select_fcn{i},x,y,z);
    end
    memb_frac = mean(memb_val,2);
end
function do_unit_test;
    imdl = mk_common_model('a2c2',8);
    select_fcn = '(x-0.2).^2+(y-0.5).^2<0.2^2';
    memb_frac = elem_select( imdl.fwd_model, select_fcn);
    unit_test_cmp('a2c2 (string)',find(memb_frac), [5, 10,18,26,27]');
    imdl = mk_common_model('a2c2',8);
    select_fcn = inline('(x-0.2).^2+(y-0.5).^2<0.2^2','x','y','z');
    memb_frac = elem_select( imdl.fwd_model, select_fcn);
    unit_test_cmp('a2c2',find(memb_frac), [5, 10,18,26,27]');
    select_fcn2= inline('y<0.4','x','y','z');
    memb_frac = elem_select( imdl.fwd_model, {select_fcn,select_fcn2});
    unit_test_cmp('a2c2 (2fcns)',find(memb_frac), [5, 10,18,27]');
    imdl = mk_common_model('n3r2',[16,2]);
    select_fcn = inline('(x-0.2).^2+(y-0.5).^2 + (z-1).^2<0.1^2','x','y','z');
    memb_frac = elem_select( imdl.fwd_model, select_fcn);
    unit_test_cmp('n3r2',find(memb_frac), [156 159 162 168 431 434 437 503]');