Description of mdl_dim
Home > eidors > models > mdl_dim.m
mdl_dim
PURPOSE
MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
SYNOPSIS
function num = mdl_dim(mdl);
DESCRIPTION
 MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
  Note, mdl_dims is not the same as the element dimentions
 num_dim = mdl_dim( mdl );
    = 2 if 2D, 3 if 3D
 If there is a vector of mdls, return the dimension of the first
CROSS-REFERENCE INFORMATION
This function calls:
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
eval_GREIT_fig_merit EVAL_GREIT_FIG_MERIT: calculate GREIT figures of merit for images
calc_slices calc_slices (img, levels, clim) show slices at levels of an
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
ng_mk_common_model NG_MK_COMMON_MODEL: utility to create common models
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
fix_model FIX_MODEL: Add useful fields to a model
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
GREIT_desired_img_sigmoid GREIT_DESIRED_IMG_SIGMOID sigmoid-decay desired image function for GREIT
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = mdl_dim(mdl);
% MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
%  Note, mdl_dims is not the same as the element dimentions
% num_dim = mdl_dim(mdl);
%    = 2 if 2D, 3 if 3D
% If there is a vector of mdls, return the dimension of the first
% $Id: mdl_dim.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if ~isfield(mdl,'type') && isfield(mdl,'nodes') % Set default for this case
   mdl.type = 'fwd_model';
end
switch mdl(1).type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.nodes,2);
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = mdl_dim( mdl );
   unit_test_cmp('test1', ne, 2);
   mdl = mk_common_model('n3r2',[16,2]);
   ne = mdl_dim( mk_image( mdl ));
   unit_test_cmp('test1', ne, 3);