Description of mdl_normalize
Home > eidors > models > mdl_normalize.m
mdl_normalize
PURPOSE
MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
SYNOPSIS
function out = mdl_normalize(mdl, val)
DESCRIPTION
MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
  OUT = MDL_NORMALIZE(MDL) returns the value of the
  'normalize_measurements' or 'normalize' field on MDL. If absent, the
  default value is returned as set with EIDORS_DEFAULT.
  MDL = MDL_NORMALIZE(MDL, VAL) sets the 'normalize_measurements' to VAL
 See also: FWD_MODEL_PARAMETERS, EIDORS_DEFAULT, EIDORS_STARTUP
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_common_model MK_COMMON_MODEL: make common EIT models
eidors_default EIDORS_DEFAULT Default function handler.
This function is called by:
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
eidors_model_params mdl = eidors_model_params(mdl);
compare_2d_algs Compare different 2D reconstructions
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_common_gridmdl MK_COMMON_MODEL: make EIT on reconstruction grids (GREIT)
mk_library_model MK_LIBRARY_MODEL - FEM models based on library shapes
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
test_GREIT_model
calc_R_prior R = calc_R_prior(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_difference_data CALC_DIFFERENCE_DATA: calculate difference data between
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
inv_solve INV_SOLVE: calculate imag from an inv_model and data
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
perturb_jacobian_test Perturbation Jacobians
test_3d_resistor Create 3D model of a Rectangular resistor
SUBFUNCTIONS
function out = get_flag(mdl)
function mdl = set_flag(mdl, val)
function do_unit_test
SOURCE CODE
function out = mdl_normalize(mdl, val)
%MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
%  OUT = MDL_NORMALIZE(MDL) returns the value of the
%  'normalize_measurements' or 'normalize' field on MDL. If absent, the
%  default value is returned as set with EIDORS_DEFAULT.
%
%  MDL = MDL_NORMALIZE(MDL, VAL) sets the 'normalize_measurements' to VAL
%
% See also: FWD_MODEL_PARAMETERS, EIDORS_DEFAULT, EIDORS_STARTUP
% (C) 2012 Bartlomiej Grychtol. License: GPL v2 or v3
% $Id: mdl_normalize.m 5227 2016-06-13 13:51:34Z aadler $
if ischar(mdl) && strcmp(mdl, 'UNIT_TEST'); do_unit_test; return; end
% check that we got a fwd_model
try
    if ~strcmp(mdl.type,'fwd_model'), error;end;
catch
    error('mdl_normalize: not called for a fwd_model object');
end
% do the real thing
switch nargin
    case 1
        out = get_flag(mdl);
        if isempty(out)
            out = feval('eidors_default');
            warning('EIDORS:normalize_flag_not_set', ...
                'normalize_measurements flag not set on model. Using default: %d',out);
        end
    case 2
        out = set_flag(mdl,val);
    otherwise
        error('Wrong number of parameters');
end
function out = get_flag(mdl)
 out = [];
% iterate over fields
ff = fieldnames(mdl);
for i = 1:length(ff);
    % if both are set, you're in trouble
    if any(strcmp(ff{i},{'normalize','normalize_measurements'}))
        out = mdl.(ff{i});
    else
        % won't hit 'normal' or anything that starts with 'normals'.
        token = regexp(ff{i},'normal[^s]+.*','match','once');
        if ~isempty(token);
            warning('Suspect field "%s" found on the model',token);
        end
    end
end
function mdl = set_flag(mdl, val)
mdl.normalize_measurements = val;
function do_unit_test
s = warning('query', 'backtrace');
warning off backtrace;
eidors_default('set','mdl_normalize',@(x) 0);
mdl = mk_common_model('c2t2',16);
fmdl = mdl.fwd_model;
eidors_msg('Does it come normalized?');
eidors_msg(mdl_normalize(fmdl));
eidors_msg('Normalize it');
fmdl = mdl_normalize(fmdl,1);
eidors_msg('How about now?');
eidors_msg(mdl_normalize(fmdl));
eidors_msg('De-normalize it');
fmdl = mdl_normalize(fmdl,0);
eidors_msg('And now?');
eidors_msg(mdl_normalize(fmdl));
eidors_msg('Remove the flag');
fmdl = rmfield(fmdl,'normalize_measurements');
eidors_msg(mdl_normalize(fmdl));
eidors_msg('And now let''s set it to something stupid');
fmdl.normalise_measurements = 1; % s, throw a warning, return default
eidors_msg(mdl_normalize(fmdl));
fmdl.normalize_my_gran = 1; % throw a warning, return default
eidors_msg(mdl_normalize(fmdl));
fmdl.normalize = 1; % accept happily
eidors_msg(mdl_normalize(fmdl));
eidors_msg('But an imdl is not acceptable!');
try
eidors_msg(mdl_normalize(mdl));
catch
    eidors_msg('Just so.');
end
warning(s);