Description of mk_coarse_fine_mapping
Home > eidors > models > mk_coarse_fine_mapping.m
mk_coarse_fine_mapping
PURPOSE
MK_COARSE_FINE_MAPPING: create a mapping matrix from coarse to fine FEM
SYNOPSIS
function [mapping, outside] = mk_coarse_fine_mapping(varargin)
DESCRIPTION
MK_COARSE_FINE_MAPPING: create a mapping matrix from coarse to fine FEM
 [c2f,out]= mk_coarse_fine_mapping( f_mdl, c_mdl, opt );
 Parameters:
    c_mdl is coarse fwd_model
    f_mdl is fine fwd_model
    opt   is option structure (optional, see below)
 This function is a compatibility wrapper. The actual calculations are
 carried out by either MK_ANALYTIC_C2F or MK_APPROX_C2F (the older
 method).
 To set a specific implementation use
    eidors_default('set','mk_coarse_fine_mapping','mk_approx_c2f');
 To query current implementation use
    eidors_default('get','mk_coarse_fine_mapping');
 NOTE that MK_ANALYTIC_C2F accepts an optional third argument whereas
 MK_APPROXIMATE_C2F does not.
 See also: EIDORS_DEFAULT, MK_ANALYTIC_C2F, MK_APPROX_C2F, CHECK_C2F_QUALITY
CROSS-REFERENCE INFORMATION
This function calls:
eidors_default EIDORS_DEFAULT Default function handler.
This function is called by:
mk_approx_c2f MK_APPROX_C2F: create a mapping matrix from coarse to fine FEM
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
get_img_data GET_IMG_DATA: get parameter data from eidors image object
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
mk_GN_model MK_GN_MODEL: make EIDORS inverse models using the GREIT approach
test_c2f_jacobian Test calc of jacobian given coarse to fine mapping
SOURCE CODE
function [mapping, outside] = mk_coarse_fine_mapping(varargin)
%MK_COARSE_FINE_MAPPING: create a mapping matrix from coarse to fine FEM
% [c2f,out]= mk_coarse_fine_mapping(f_mdl, c_mdl, opt);
%
% Parameters:
%    c_mdl is coarse fwd_model
%    f_mdl is fine fwd_model
%    opt   is option structure (optional, see below)
%
% This function is a compatibility wrapper. The actual calculations are
% carried out by either MK_ANALYTIC_C2F or MK_APPROX_C2F (the older
% method).
%
% To set a specific implementation use
%    eidors_default('set','mk_coarse_fine_mapping','mk_approx_c2f');
%
% To query current implementation use
%    eidors_default('get','mk_coarse_fine_mapping');
%
% NOTE that MK_ANALYTIC_C2F accepts an optional third argument whereas
% MK_APPROXIMATE_C2F does not.
%
% See also: EIDORS_DEFAULT, MK_ANALYTIC_C2F, MK_APPROX_C2F, CHECK_C2F_QUALITY
% (C) 2015 Bartlomiej Grychtol
% License: GPL version 2 or version 3
% $Id: mk_coarse_fine_mapping.m 5640 2017-09-05 16:00:41Z alistair_boyle $
[mapping, outside] = eidors_default(varargin{:});