Description of mk_image
Home > eidors > models > mk_image.m
mk_image
PURPOSE
MK_IMAGE: create eidors image object
SYNOPSIS
function img= mk_image(mdl, elem_data, params, name)
DESCRIPTION
 MK_IMAGE: create eidors image object
   img= mk_image(mdl, elem_data, name)
 Utility function to create an eidors_image object:
 Usage 1:
   img = mk_image( inv_model )  -> uses jacobian backgnd for conductivity
 Usage 2: mdl can be a fwd_model or inv_model
   img = mk_image( mdl, 1 ) -> uniform image with conductivity 1
   img = mk_image( mdl, 2*ones(n_elems,1) ) -> uniform with c=2
   img = mk_image( mdl, 2*ones(n_nodes,1) ) -> image with node data
   img = mk_image( mdl, 1, 'This name') -> Specify a 'name' attribute
   img = mk_image( mdl, ones(n_elems,3) );
 Usage 3: create image from previous image, override conductity
  img = mk_image( other_image, 2 ) -> image with c=2
 Usage 4: create image with specific 'params' properties
  img = mk_image( mdl, 3*ones(64,1),'resistivity' ); % resistivity image
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
data_mapper DATA_MAPPER maps img.params data to elem or node data
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
supported_params
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
ex_fwd2d_high_order ensure dev/m_crabb/forward_problem is on the path
ex_fwd3d_high_order Make common model, and make an image
resistor_model DEMO to show really simple application of EIDORS framework
calc_slices calc_slices (img, levels, clim) show slices at levels of an
eidors_colourbar EIDORS_COLOURBAR - create an eidors colourbar with scaling to image
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
mdl_slice_mesher MDL_SLICE_MESHER A slice of a 3D FEM as a 2D FEM
print_convert PRINT_CONVERT: print figures with anti-aliasing and trim them
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts, any_cuts)
show_current SHOW_CURRENT: show current or other quantity defined
show_fem_move SHOW_FEM_MOVE Plot EIT finite element model (FEM) and movement
show_pseudosection SHOW_PSEUDOSECTION: show a pseudo-section image of data
show_slices_move SHOW_SLICES_MOVE Shows planar slices of a 3D FEM with movement vectors
sigmatome2_filter SIGMATOME2_FILTER: Hardware filter and stim_patterns for Sigmatome II device
ng_mk_ellip_models NG_MAKE_ELLIP_MODELS: create elliptical models using netgen
ng_mk_gen_models NG_MK_GEN_MODELS: create generic models using netgen
GREIT3D_distribution GREIT3D_distribution: create target distributions for 3D GREIT
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
calc_elem_current calc_elem_current: calculate current vector in each FEM element
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
check_c2f_quality CHECK_C2F_QUALITY Check the coarse2fine mapping between two models
data_mapper DATA_MAPPER maps img.params data to elem or node data
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_image MK_IMAGE: create eidors image object
mk_library_model MK_LIBRARY_MODEL - FEM models based on library shapes
mk_lung_image MK_LUNG_IMAGE create an image with lung and heart contrasts from a model
mk_pixel_slice MK_PIXEL_SLICE create a pixel model to reconstruct on
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
mk_voxel_volume MK_VOXEL_VOLUME create a voxel model to reconstruct on
num_elecs NUM_ELECS: number of electrodes attached to model
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
select_imdl SELECT_IMDL: select pre-packaged inverse model features
solve_RM_2Dslice SOLVE_RM_2DSLICE: cut slices out of a 3D model
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
test_GREIT_model
eit_spice function spice = eit_spice(img, [name])
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_apparent_resistivity fwd_solve_apparent_resistivity: fwd_solve output as apparent resistivity
fwd_solve_halfspace FWD_SOLVE_HALFSPACE: data = fwd_solve_halfspace(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
inv_solve INV_SOLVE: calculate imag from an inv_model and data
GREIT_desired_img_sigmoid GREIT_DESIRED_IMG_SIGMOID sigmoid-decay desired image function for GREIT
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
inv_solve_abs_annealingMetropolis_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_abs_annealingSimplex_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_cg function img= inv_solve_cg(inv_model, data1);
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_gn function img= inv_solve_gn(inv_model, data1);
mk_GN_model MK_GN_MODEL: make EIDORS inverse models using the GREIT approach
prior_exponential_covar PRIOR_EXPONENTIAL_COVAR image prior with exponential
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function str = no_params
function img = fill_in_data(img,elem_data,params)
function do_unit_test
SOURCE CODE
function img= mk_image(mdl, elem_data, params, name)
% MK_IMAGE: create eidors image object
%   img= mk_image(mdl, elem_data, name)
%
% Utility function to create an eidors_image object:
% Usage 1:
%   img = mk_image(inv_model)  -> uses jacobian backgnd for conductivity
%
% Usage 2: mdl can be a fwd_model or inv_model
%   img = mk_image(mdl, 1) -> uniform image with conductivity 1
%   img = mk_image(mdl, 2*ones(n_elems,1)) -> uniform with c=2
%   img = mk_image(mdl, 2*ones(n_nodes,1)) -> image with node data
%   img = mk_image(mdl, 1, 'This name') -> Specify a 'name' attribute
%   img = mk_image(mdl, ones(n_elems,3));
%
% Usage 3: create image from previous image, override conductity
%  img = mk_image(other_image, 2) -> image with c=2
%
% Usage 4: create image with specific 'params' properties
%  img = mk_image(mdl, 3*ones(64,1),'resistivity'); % resistivity image
% (C) 2008-12 Andy Adler and Bartlomiej Grychtol.
% Licenced under GPL version 2 or 3
% $Id: mk_image.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
default_params = no_params; % later: conductivity ?
default_name    = 'Created by mk_image';
if nargin<3
    name = default_name;
    params = default_params;
elseif nargin < 4 % preserve old interface
    if ismember(params,supported_params)
        name = default_name;
    else
        name = params;
        params = default_params;
    end
end
% if nargin<2;
%    try
%      elem_data = mdl.jacobian_bkgnd.value;
%    catch
%      error('mk_image: for one parameter, needs a mdl.jacobian_bkgnd field');
%    end
% end
switch mdl.type
   case 'inv_model'
      if nargin == 1
         img = calc_jacobian_bkgnd(mdl);
         return
      else
         mdl = mdl.fwd_model;
         % warning('Ignoring inv_model.jacobian_bkgnd in favour of the supplied elem_data');
      end
   case 'fwd_model'
      mdl = mdl; % keep model
   case 'image'
      if nargin == 1
         img = data_mapper(mdl);
         return
      end
      mdl = mdl.fwd_model;
   otherwise; error('mk_image: no inv_model, fwd_model or image object');
end
img = eidors_obj('image',name);
img.fwd_model = mdl;
if isfield(mdl,'show_slices');
    img.show_slices = mdl.show_slices;
end
img = fill_in_data(img,elem_data,params);
% img.current_params = params;
function str = no_params
str = 'unspecified';
function img = fill_in_data(img,elem_data,params)
  % If image is presented as row vector, then transpose
  %  Shouldn't happen, but for matlab bugs
  if size(elem_data,1) == 1 && ...
     size(elem_data,2) >  1
     elem_data = elem_data.';
  end
  switch size(elem_data,1)
     case 1
        sz = size(img.fwd_model.elems,1);
        elem_data_mat =    NaN*ones(sz,1);
        elem_data_mat(:) = elem_data;
        if strcmp(params,no_params);
            img.elem_data = elem_data_mat;
        else
            img.(params).elem_data = elem_data_mat;
        end
     case num_elems( img )
        if strcmp(params,no_params);
            img.elem_data = elem_data;
        else
            img.(params).elem_data = elem_data;
        end
     case size(img.fwd_model.coarse2fine,2)
        if strcmp(params,no_params);
            img.elem_data = elem_data;
        else
            img.(params).elem_data = elem_data;
        end
     case num_nodes( img )
        if strcmp(params,no_params);
            img.node_data = elem_data;
        else
            img.(params).node_data = elem_data;
        end
     otherwise
        error('Don''t understand number of elements.');
  end
% TESTS:
function do_unit_test
   imdl = mk_common_model('a2c2',8);
   im0 = mk_image( imdl );
   unit_test_cmp('im1',im0.elem_data, ones(64,1) );
   im0 = mk_image( imdl, 2 ); % warning
   unit_test_cmp('im2',im0.elem_data, 2*ones(64,1) );
   im0 = mk_image( imdl.fwd_model, 3*ones(64,1) );
   unit_test_cmp('im3',im0.elem_data, 3*ones(64,1) );
   im0 = mk_image(im0); % no change
   unit_test_cmp('im4',im0.elem_data, 3*ones(64,1) );
   im0.conductivity.elem_data = im0.elem_data;
   im0 = rmfield(im0, 'elem_data');
   im1 = mk_image(im0); % use data_mapper
   unit_test_cmp('im5',im1.elem_data, 3*ones(64,1) );
   im0.resistivity.node_data = 5;
   im0.data_mapper = 'resistivity';
   im1 = mk_image(im0); % use data_mapper
   unit_test_cmp('im6',im1.node_data(5), 5 );
   imdl.jacobian_bkgnd = rmfield(imdl.jacobian_bkgnd, 'value');
   imdl.jacobian_bkgnd.conductivity = im0.conductivity;
   im2 = mk_image(imdl);
   unit_test_cmp('im7',im2.conductivity.elem_data, 3*ones(64,1) );
   im0 = mk_image( imdl.fwd_model, 3*ones(64,1),'my_name' );
   unit_test_cmp('im8a',im0.elem_data, 3*ones(64,1) );
   im0 = mk_image( imdl.fwd_model, 3*ones(64,1),'resistivity' );
   unit_test_cmp('im8b',im0.resistivity.elem_data, 3*ones(64,1) );
   im0 = mk_image( imdl.fwd_model, 2*ones(64,3),'resistivity' );
   unit_test_cmp('im8c',im0.resistivity.elem_data, 2*ones(64,3) );
   im0 = mk_image( imdl.fwd_model, 3*ones(64,1),'resistivity','my name' );
   unit_test_cmp('im9a',im0.resistivity.elem_data, 3*ones(64,1) );
   unit_test_cmp('im9b',im0.name, 'my name' );