Description of num_elems
Home > eidors > models > num_elems.m
num_elems
PURPOSE
NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
SYNOPSIS
function num = num_elems(mdl);
DESCRIPTION
 NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
 num_elems = num_elems( mdl );
CROSS-REFERENCE INFORMATION
This function calls:
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts, any_cuts)
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
fix_model FIX_MODEL: Add useful fields to a model
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
linear_reorder [fwd_model] = linear_reorder(fwd_model,ccw)
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_image MK_IMAGE: create eidors image object
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
calc_solution_error CALC_SOLUTION_ERROR Calculate residuals for a solution
test_2d_resistor Create 2D model of a cylindrical resistor
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = num_elems(mdl);
% NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
% num_elems = num_elems(mdl);
% $Id: num_elems.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
if ~isfield(mdl,'type') && isfield(mdl,'elems') % Set default for this case
   mdl.type = 'fwd_model';
end
switch mdl.type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.elems,1);
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = num_elems( mdl );
   unit_test_cmp('test1',ne, 64);
   ne = num_elems( mdl.fwd_model );
   unit_test_cmp('test2',ne, 64);
   ne = num_elems( mk_image( mdl ));
   unit_test_cmp('test3',ne, 64);
   mdl = mk_common_model('n3r2',[16,2]);
   ne = num_elems( mk_image( mdl ));
   unit_test_cmp('test4',ne, 828);