Description of num_nodes
Home > eidors > models > num_nodes.m
num_nodes
PURPOSE
NUM_NODES: number of elemnts in a (fwd or inv model or image)
SYNOPSIS
function num = num_nodes(mdl);
DESCRIPTION
 NUM_NODES: number of elemnts in a (fwd or inv model or image)
 n_nodes = num_nodes( mdl );
CROSS-REFERENCE INFORMATION
This function calls:
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts, any_cuts)
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
show_fem_move SHOW_FEM_MOVE Plot EIT finite element model (FEM) and movement
join_models JOIN_MODELS: Join two fmdl structures to create one
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_image MK_IMAGE: create eidors image object
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
eit_spice function spice = eit_spice(img, [name])
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
get_img_data GET_IMG_DATA: get parameter data from eidors image object
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function num = num_nodes(mdl);
% NUM_NODES: number of elemnts in a (fwd or inv model or image)
% n_nodes = num_nodes(mdl);
% $Id: num_nodes.m 5112 2015-06-14 13:00:41Z aadler $
if ischar(mdl) && strcmp(mdl,'UNIT_TEST'); do_unit_test; return; end
switch mdl.type
  case 'image';      fmdl = mdl.fwd_model;
  case 'inv_model';  fmdl = mdl.fwd_model;
  case 'fwd_model';  fmdl = mdl;
  otherwise;
      error('can''t process model of type %s', mdl.type );
end
num = size(fmdl.nodes,1);
function do_unit_test
   mdl = mk_common_model('a2c2',8);
   ne = num_nodes( mdl );
   unit_test_cmp('test1',ne,41);
   ne = num_nodes( mdl.fwd_model );
   unit_test_cmp('test2',ne,41);
   ne = num_nodes( mk_image( mdl ));
   unit_test_cmp('test3',ne,41);
   mdl = mk_common_model('n3r2',[16,2]);
   ne = num_nodes( mk_image( mdl ));
   unit_test_cmp('test4',ne,252);