Description of supported_params
Home > eidors > models > supported_params.m
supported_params
PURPOSE
SYNOPSIS
function list = supported_params
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
data_mapper DATA_MAPPER maps img.params data to elem or node data
mk_image MK_IMAGE: create eidors image object
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_halfspace FWD_SOLVE_HALFSPACE: data = fwd_solve_halfspace(img)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
inv_solve INV_SOLVE: calculate imag from an inv_model and data
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
SOURCE CODE
function list = supported_params
   list = {'conductivity'
           'log_conductivity'
           'log10_conductivity'
           'resistivity'
           'log_resistivity'
           'log10_resistivity'
           'movement'};
end