Description of mapper_nodes_elems
Home > eidors > deprecated > mapper_nodes_elems.m
mapper_nodes_elems
PURPOSE
MAPPER_ELEMS_NODES: calculates mapping function taking elems to nodes
SYNOPSIS
function EtoN= mapper_elems_nodes(fwd_model)
DESCRIPTION
 MAPPER_ELEMS_NODES: calculates mapping function taking elems to nodes
 EtoN= mapper_elems_nodes(fwd_model)
 EtoN is a matrix [Nnodes x Nelems]
    where [EtoN]_ij = 1/3 if elem_j shares node_i
CROSS-REFERENCE INFORMATION
This function calls:
sparse SPARSE Create sparse matrix (EIDORS overload).
This function is called by:
jacobian_elem2nodes JACOBIAN_ELEM2NODES: calculate Jacobian on Nodes from Elem solver
RtR_prior_elem2nodes RtR_PRIOR_ELEM2NODES: Convert elem to nodal RtR Image Prior
SOURCE CODE
function EtoN= mapper_elems_nodes(fwd_model)
% MAPPER_ELEMS_NODES: calculates mapping function taking elems to nodes
% EtoN= mapper_elems_nodes(fwd_model)
% EtoN is a matrix [Nnodes x Nelems]
%    where [EtoN]_ij = 1/3 if elem_j shares node_i
warning('EIDORS:deprecated','MAPPER_ELEMS_NODES is deprecated as of 27-Jun-2012.');
elems= fwd_model.elems;
n_elems= size(elems,1);
n_dimp1= size(elems,2);
n_nodes= size(fwd_model.nodes,1);
EtoN = sparse(elems, (1:n_elems)'*ones(1,n_dimp1), 1/3, n_nodes, n_elems);