Description of sparse
Home > eidors > overloads > sparse.m
sparse
PURPOSE
SPARSE Create sparse matrix (EIDORS overload).
SYNOPSIS
function S = sparse(varargin)
DESCRIPTION
SPARSE Create sparse matrix (EIDORS overload).
   S = SPARSE(X) converts a sparse or full matrix to sparse form by
   squeezing out any zero elements.
  See also SPARFUN/SPARSE
 Sparse doesn't work for uint* inputs, so we need to preconvert to double
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bld_master function [Ef,D,Ela] = bld_master(vtx,simp,mat_ref);
bld_master_full function [Ef,D,Ela] = bld_master_full(vtx,simp,mat,elec,zc);
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
integrofgrad function [IntGrad] = integrofgrad(vtx,simp,mat_ref);
mapper_nodes_elems MAPPER_ELEMS_NODES: calculates mapping function taking elems to nodes
cheating_2d code to simulate inverse crimes in EIT
demo_real [inhomg_img, demo_img] = demo_real;
mdl_slice_mesher MDL_SLICE_MESHER A slice of a 3D FEM as a 2D FEM
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
eidors_readdata EIDORS readdata - read data files from various EIT equipment
sigmatome2_filter SIGMATOME2_FILTER: Hardware filter and stim_patterns for Sigmatome II device
calc_mesh_quality CALC_MESH_QUALITY Various measures of mesh quality.
distmesh2d DISTMESH2D 2-D Mesh Generator using Distance Functions.
distmeshnd DISTMESHND N-D Mesh Generator using Distance Functions.
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
deform_cylinder fwd_mdl = deform_cylinder(fwd_mdl, niv);
find_edge2edge_intersections FIND_EDGE2EDGE_INTERSECTIONS intersections between edges of two models
fix_model FIX_MODEL: Add useful fields to a model
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
mk_approx_c2f MK_APPROX_C2F: create a mapping matrix from coarse to fine FEM
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
place_elec_on_surf PLACE_ELEC_ON_SURF Place electrodes on the surface of a model
point_in_tet POINT_IN_TET test for points contained in elements
point_in_triangle POINT_IN_TRIANGLE tests points for membership in triangles
simulate_2d_movement SIMULATE_2D_MOVEMENT simulate rotational movement in 2D
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
calc_transferimpedance CALC_TRANSFERIMPEDANCE: Calculates transfer impedance matrix
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
spice_eit Vn = spice_eit(netlist, [freq])
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_fields SYSTEM_MAT_2P5D_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_higher_order Assemble the total stiffness matrix : s_mat.E=At;
update_system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
GREIT_desired_img_sigmoid GREIT_DESIRED_IMG_SIGMOID sigmoid-decay desired image function for GREIT
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
prior_exponential_covar PRIOR_EXPONENTIAL_COVAR image prior with exponential
prior_gaussian_HPF PRIOR_GAUSSIAN_HPF calculate image prior
prior_laplace PRIOR_LAPLACE calculate image prior
prior_laplace_old PRIOR_LAPLACE calculate image prior
prior_movement PRIOR_MOVEMENT calculate image prior
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SOURCE CODE
function S = sparse(varargin)
%SPARSE Create sparse matrix (EIDORS overload).
%   S = SPARSE(X) converts a sparse or full matrix to sparse form by
%   squeezing out any zero elements.
%
%  See also SPARFUN/SPARSE
%
% Sparse doesn't work for uint* inputs, so we need to preconvert to double
% (C) 2011 Bartlomiej Grychtol. License: GPL v2 or v3.
% $Id: sparse.m 3489 2012-07-04 09:39:43Z aadler $
for i= 1:nargin
  varargin{i} = double(varargin{i});
end
S = builtin('sparse',varargin{:});