Description of spdiag
Home > eidors > overloads > spdiag.m
spdiag
PURPOSE
SPDIAG Sparse diagonal matrices and diagonals of a matrix.
SYNOPSIS
function S = spdiag(V,K)
DESCRIPTION
SPDIAG Sparse diagonal matrices and diagonals of a matrix.
 This is a sparse version of matlab's diag command, see the
 help of that command for its use.
 See also: DIAG, SPDIAGS
 (C) 2013 Andy Adler. License GPL v2 or v3
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mdl_slice_mesher MDL_SLICE_MESHER A slice of a 3D FEM as a 2D FEM
system_mat_2p5d_fields SYSTEM_MAT_2P5D_FIELDS: fields (elem to nodes) fraction of system mat
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
meas_icov_rm_elecs MEAS_ICOV_RM_ELECS: remove electrodes from consideration
SOURCE CODE
function S = spdiag(V,K)
%SPDIAG Sparse diagonal matrices and diagonals of a matrix.
%
% This is a sparse version of matlab's diag command, see the
% help of that command for its use.
%
% See also: DIAG, SPDIAGS
%
% (C) 2013 Andy Adler. License GPL v2 or v3
% Matlab's spdiags is really annoying. This function provides
%  an interface like G-d intended
if nargin == 1; K=0; end
N = length(V) + K;
V = [zeros(K,1);V(:)];
S = spdiags(V(:), K, N, N);