Description of calc_hyperparameter
Home > eidors > solvers > calc_hyperparameter.m
calc_hyperparameter
PURPOSE
CALC_HYPERPARAMETER: calculate hyperparameter value
SYNOPSIS
function hyperparameter = calc_hyperparameter(inv_model)
DESCRIPTION
 CALC_HYPERPARAMETER: calculate hyperparameter value
   The hyperparameter is can be either provided directly,
     or can be based an automatic selection approach
 calc_hyperparameter can be called as
    hyperparameter= calc_hyperparameter( inv_model )
 where inv_model    is an inv_model structure
 if inv_model.hyperparameter.func exists, it will be
   called, otherwise inv_model.hyperparameter.value will
   be returned
 TODO: does hyperparameter depend on inv_model, or does
       it also depend on the data?
CROSS-REFERENCE INFORMATION
This function calls:
eidors_cache EIDORS_CACHE Control eidors caching
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
inv_solve_dual_mesh INV_SOLVE_DUAL_MESH using a coarse and fine mesh
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
get_RM % GET_RM: obtains the reconstruction matrix from a given inverse model
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_TV_pdipm INV_SOLVE_TV_PDIPM inverse solver for Andrea Borsic's
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
SOURCE CODE
function hyperparameter = calc_hyperparameter(inv_model)
% CALC_HYPERPARAMETER: calculate hyperparameter value
%   The hyperparameter is can be either provided directly,
%     or can be based an automatic selection approach
%
% calc_hyperparameter can be called as
%    hyperparameter= calc_hyperparameter(inv_model)
% where inv_model    is an inv_model structure
%
% if inv_model.hyperparameter.func exists, it will be
%   called, otherwise inv_model.hyperparameter.value will
%   be returned
%
% TODO: does hyperparameter depend on inv_model, or does
%       it also depend on the data?
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_hyperparameter.m 4836 2015-03-30 07:19:25Z aadler $
if isfield(inv_model.hyperparameter, 'func')
   try inv_model.hyperparameter = str2func(inv_model.hyperparameter); end
   hyperparameter = eidors_cache(...
                    inv_model.hyperparameter.func,{inv_model},'hyperparameter');
else
    hyperparameter= inv_model.hyperparameter.value;
end