Description of calc_difference_data
Home > eidors > solvers > calc_difference_data.m
calc_difference_data
PURPOSE
CALC_DIFFERENCE_DATA: calculate difference data between
SYNOPSIS
function dva = calc_difference_data(data1, data2, fwd_model)
DESCRIPTION
 CALC_DIFFERENCE_DATA: calculate difference data between
   two eidors data vectors
 dva = calc_difference_data( meas1, meas2, fwd_model)
  dva   = Matrix n_meas x n_time_steps of difference meas
  meas1 = measurement object (or matrix) at time1 (homogeneous)
  meas2 = measurement object (or matrix) at time2 (inhomogeneous)
  fwd_model (optional, if provided in meas1 and meas2)
  if data1==0, then just process data2 like absolute data
 This code appears simple, but there are a number of tricks
  to remember, so it is best to factor it out. Issues are
  1) normalize_data, 2) remove zero meas from adjacent systems,
  3) allow both raw data and eidors_obj formats for data
CROSS-REFERENCE INFORMATION
This function calls:
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
This function is called by:
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
calc_reciproc_error CALC_RECIPROC_ERROR: CALCULATE RECIPROCITY ERROR MATRIX
calc_solution_error CALC_SOLUTION_ERROR Calculate residuals for a solution
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_TV_pdipm INV_SOLVE_TV_PDIPM inverse solver for Andrea Borsic's
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_backproj INV_SOLVE_BACKPROJ inverse solver using backprojection
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
line_optimize LINE_OPTIMIZE Cheap line optimizer
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
solve_use_matrix SOLVE_USE_MATRIX solve using reconstruction matrix
SUBFUNCTIONS
function nf= num_frames(d0)
function d2= filt_data(fwd_model, d0, data_width)
SOURCE CODE
function dva = calc_difference_data(data1, data2, fwd_model)
% CALC_DIFFERENCE_DATA: calculate difference data between
%   two eidors data vectors
% dva = calc_difference_data(meas1, meas2, fwd_model)
%
%  dva   = Matrix n_meas x n_time_steps of difference meas
%  meas1 = measurement object (or matrix) at time1 (homogeneous)
%  meas2 = measurement object (or matrix) at time2 (inhomogeneous)
%  fwd_model (optional, if provided in meas1 and meas2)
%
%  if data1==0, then just process data2 like absolute data
%
% This code appears simple, but there are a number of tricks
%  to remember, so it is best to factor it out. Issues are
%  1) normalize_data, 2) remove zero meas from adjacent systems,
%  3) allow both raw data and eidors_obj formats for data
% (C) 2006 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_difference_data.m 3351 2012-07-01 21:37:37Z aadler $
data_width= max(num_frames(data1), num_frames(data2));
try if data1.type == 'data'
   data1= data1.meas;
end; end
try if data2.type == 'data'
   data2= data2.meas;
end; end
if all(size(data1) == [1,1]) && (data1 == 0)
   dva =  filt_data( fwd_model, data2, data_width );
   return;
end
fwd_model = mdl_normalize(fwd_model,mdl_normalize(fwd_model));
fdata1 = filt_data(fwd_model, data1, data_width);
fdata2 = filt_data(fwd_model, data2, data_width);
if mdl_normalize(fwd_model)
   dva= fdata2 ./ fdata1 - 1;
else
   dva= fdata2 - fdata1;
end
function nf= num_frames(d0)
   if isnumeric( d0 )
      nf= size(d0,2);
   elseif strcmp( d0(1).type, 'data' );
      nf= size(horzcat(d0(:).meas),2);
   else
      error('Problem calculating number of frames');
   end
% test for existance of meas_select and filter data
function d2= filt_data(fwd_model, d0, data_width)
   if ~isnumeric( d0 )
       % we probably have a 'data' object
       l_obj = length(d0);
       d1 = zeros( length( d0(1).meas ), l_obj);
       for i=1:l_obj
          if strcmp( d0(i).type, 'data' )
              d1(:,i) = d0(i).meas;
          else
              error('expecting an object of type data');
          end
       end
   else
      % we have a matrix of data. Hope for the best
      d1 = d0;
   end
   d1= double(d1); % ensure we can do math on our object
   if isfield(fwd_model,'meas_select') && ...
     ~isempty(fwd_model.meas_select);
      % we have a meas_select parameter
      meas_select= fwd_model.meas_select;
      if     size(d1,1) == length(meas_select)
         d2= d1(meas_select,:);
      elseif size(d1,1) == sum(meas_select==1)
         d2= d1;
      else
         error('data size does not match meas_select');
      end
   else
      d2= d1;
   end
   if nargin==3 % expand to data width
      d2_width= size(d2,2);
      if d2_width == data_width
         % ok
      elseif d2_width == 1
         d2= d2(:,ones(1,data_width));
      else
         error('inconsistent difference data: (%d ~= %d)',  ...
               d2_width, data_width);
      end
   end