Description of calc_jacobian
Home > eidors > solvers > calc_jacobian.m
calc_jacobian
PURPOSE
CALC_JACOBIAN: calculate jacobian from an inv_model
SYNOPSIS
function J = calc_jacobian(fwd_model, img)
DESCRIPTION
 CALC_JACOBIAN: calculate jacobian from an inv_model
  J = calc_jacobian( img )
      calc Jacobian on img.fwd_model at conductivity given
      in image (fwd_model is for forward and reconstruction)
 The actual work is done by the jacobian calculator specified in
    img.fwd_model.jacobian, unless that field is numeric, in which case
    calc_jacobian returns its contents.
 For reconstructions on dual meshes, the interpolation matrix
    is defined as img.fwd_model.coarse2fine. This takes
    coarse2fine * x_coarse = x_fine
 If the underlying jacobian calculator doesn't understand dual
    meshes, then calc_jacobian will automatically postmultiply
    by fwd_model.coarse2fine.
 img       is an image structure, with 'elem_data' or
           'node_data' parameters
CROSS-REFERENCE INFORMATION
This function calls:
data_mapper DATA_MAPPER maps img.params data to elem or node data
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
eidors_cache EIDORS_CACHE Control eidors caching
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
resistor_model DEMO to show really simple application of EIDORS framework
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_elem2nodes JACOBIAN_ELEM2NODES: calculate Jacobian on Nodes from Elem solver
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_lambda_regtools % CALC_LAMBDA_REGTOOLS: Find optimal hyperparameter by the L-curve (LCC)
get_RM % GET_RM: obtains the reconstruction matrix from a given inverse model
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
prior_exponential_covar PRIOR_EXPONENTIAL_COVAR image prior with exponential
prior_noser PRIOR_NOSER calculate image prior
calc_data_prior_test Verify dataprior:
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
perturb_jacobian_test Perturbation Jacobians
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function cache_obj= jacobian_cache_params(fwd_model, img);
function fwd_model_check(fmdl)
SOURCE CODE
function J = calc_jacobian(fwd_model, img)
% CALC_JACOBIAN: calculate jacobian from an inv_model
%
%  J = calc_jacobian(img)
%      calc Jacobian on img.fwd_model at conductivity given
%      in image (fwd_model is for forward and reconstruction)
%
% The actual work is done by the jacobian calculator specified in
%    img.fwd_model.jacobian, unless that field is numeric, in which case
%    calc_jacobian returns its contents.
%
% For reconstructions on dual meshes, the interpolation matrix
%    is defined as img.fwd_model.coarse2fine. This takes
%    coarse2fine * x_coarse = x_fine
%
% If the underlying jacobian calculator doesn't understand dual
%    meshes, then calc_jacobian will automatically postmultiply
%    by fwd_model.coarse2fine.
%
% img       is an image structure, with 'elem_data' or
%           'node_data' parameters
% (C) 2005-08 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_jacobian.m 4832 2015-03-29 21:13:53Z bgrychtol-ipa $
if nargin == 1
   img= fwd_model;
else
   warning('EIDORS:DeprecatedInterface', ...
      ['Calling CALC_JACOBIAN with two arguments is deprecated and will cause' ...
       ' an error in a future version. First argument ignored.']);
end
ws = warning('query','EIDORS:DeprecatedInterface');
warning off EIDORS:DeprecatedInterface
try
   fwd_model= img.fwd_model;
catch
   error('CALC_JACOBIAN requires an eidors image structure');
end
fwd_model_check(fwd_model);
if isnumeric(fwd_model.jacobian)             % we have the Jacobian matrix
   J = fwd_model.jacobian;
else                                         % we need to calculate
   copt.cache_obj= jacobian_cache_params( fwd_model, img );
   copt.fstr = 'jacobian';
   try
       fwd_model.jacobian = str2func(fwd_model.jacobian);
   end
   J = eidors_cache(fwd_model.jacobian, {fwd_model, img}, copt);
end
if isfield(fwd_model,'coarse2fine')
   c2f= fwd_model.coarse2fine;
   if size(J,2)==size(c2f,1)
%     calc_jacobian did not take into account the coarse2fine
      J=J*c2f;
   end
end
warning(ws.state, 'EIDORS:DeprecatedInterface');
% Make the Jacobian only depend on
function cache_obj= jacobian_cache_params(fwd_model, img);
   img = data_mapper(img);
   if isfield(img, 'elem_data')
      cache_obj = {fwd_model, img.elem_data, img.current_params};
   elseif isfield(img, 'node_data')
      cache_obj = {fwd_model, img.node_data, img.current_params};
   else
      error('calc_jacobian: execting elem_data or node_data in image');
   end
function fwd_model_check(fmdl)
pp = fwd_model_parameters(fmdl); % they cache, so no problem
if pp.n_elec == 0
    error('Cannot calculate Jacobian. No electrodes found.');
end
if pp.n_stim == 0
    error('Cannot calculate Jacobian. No stimulation found.');
end
if pp.n_meas == 0
    error('Cannot calculate Jacobian. No measurements found.');
end