Description of calc_jacobian_bkgnd
Home > eidors > solvers > calc_jacobian_bkgnd.m
calc_jacobian_bkgnd
PURPOSE
CALC_JACOBIAN_BKGND: calculate background image around
SYNOPSIS
function img_bkgnd = calc_jacobian_bkgnd(inv_model)
DESCRIPTION
 CALC_JACOBIAN_BKGND: calculate background image around
    which initial estimate of jacobian is calculated
 img_bkgnd = calc_jacobian_bkgnd( inv_model )
 inv_model   is an EIDORS fwd_model
 img_bkgnd   is an EIDORS struct
 Usage:
      The background for calc_jacobian may be specified
      as an estimated value
  inv_model.jacobian_bkgnd.value;  % scalar OR
                                   % vector of Nx1
 Usage:
      The background may be calculated by a function
  inv_model.jacobian_bkgnd.func;
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
mk_common_model MK_COMMON_MODEL: make common EIT models
supported_params
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
eidors_cache EIDORS_CACHE Control eidors caching
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
ab_tv_lagged_diff AB_TV_LAGGED_DIFF Lagged Diffusivity Inverse Solver
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
calc_slices calc_slices (img, levels, clim) show slices at levels of an
show_current SHOW_CURRENT: show current or other quantity defined
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM: show the EIDORS3D finite element model
show_slices out_img = show_slices (img, levels) show slices at levels of an
calc_elem_current calc_elem_current: calculate current vector in each FEM element
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_image MK_IMAGE: create eidors image object
calc_JiRtRJt [JiRtRJt,iRtRJt] = calc_JiRtRJt(inv_model, varargin)
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
get_img_data GET_IMG_DATA: get parameter data from eidors image object
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_lambda_regtools % CALC_LAMBDA_REGTOOLS: Find optimal hyperparameter by the L-curve (LCC)
calc_solution_error CALC_SOLUTION_ERROR Calculate residuals for a solution
get_RM % GET_RM: obtains the reconstruction matrix from a given inverse model
inv_solve_TV_irls INV_SOLVE_TV_IRLS Iteratively Reweighted Least Squares inverse solver
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
inv_solve_diff_pdipm INV_SOLVE_DIFF_PDIPM inverse solver for difference data using Primal/Dual interior point method
inv_solve_mcmc NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
inv_solve_time_prior INV_SOLVE_TIME_PRIOR inverse solver to account for time differences
inv_solve_trunc_iterative INV_SOLVE_TRUNC_ITERATIVE using Morozov truncated iteration
nodal_solve NODAL_SOLVE inverse solver using approach of Adler&Guardo 1996
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
prior_noser PRIOR_NOSER calculate image prior
perturb_jacobian_test Perturbation Jacobians
test_c2f_jacobian Test calc of jacobian given coarse to fine mapping
test_compl_elec_mdl Test formation of complete electrode model
SUBFUNCTIONS
function img_bkgnd = jacobian_bkgnd(inv_model)
function b = has_params(s)
function do_unit_test
SOURCE CODE
function img_bkgnd = calc_jacobian_bkgnd(inv_model)
% CALC_JACOBIAN_BKGND: calculate background image around
%    which initial estimate of jacobian is calculated
%
% img_bkgnd = calc_jacobian_bkgnd(inv_model)
% inv_model   is an EIDORS fwd_model
% img_bkgnd   is an EIDORS struct
%
% Usage:
%      The background for calc_jacobian may be specified
%      as an estimated value
%  inv_model.jacobian_bkgnd.value;  % scalar OR
%                                   % vector of Nx1
%
% Usage:
%      The background may be calculated by a function
%  inv_model.jacobian_bkgnd.func;
% (C) 2005-2012 Andy Adler and Bartlomiej Grychtol
% License: GPL version 2 or version 3
% $Id: calc_jacobian_bkgnd.m 5430 2017-04-26 00:58:19Z aadler $
if ischar(inv_model) && strcmp(inv_model,'UNIT_TEST') do_unit_test; return;end
img_bkgnd = eidors_cache(@jacobian_bkgnd,{inv_model},'calc_jacobian_bkgnd');
function img_bkgnd = jacobian_bkgnd(inv_model)
%%% old interface %%%
if isfield(inv_model.jacobian_bkgnd,'func')
   img_bkgnd= feval( inv_model.jacobian_bkgnd.func, inv_model );
elseif isfield(inv_model.jacobian_bkgnd,'value')
   if has_params(inv_model.jacobian_bkgnd)
      warning('Ignoring parametrization-specific fields in Jacobian background')
   end
   % allow bkgnd to be scalar or vector
   fwd_model= inv_model.fwd_model;
   bkgnd = ones(size(fwd_model.elems,1),1);
   bkgnd(:)= inv_model.jacobian_bkgnd.value;
   img_bkgnd= eidors_obj('image', 'background image', ...
                         'elem_data', bkgnd, ...
                         'fwd_model', fwd_model );
else
%%% new interface with parametrizations (params) %%%
    fwd_model = inv_model.fwd_model;
    img_bkgnd = eidors_obj('image','background image','fwd_model',fwd_model);
    flds = fieldnames(inv_model.jacobian_bkgnd);
    % copy params from img
    for i = 1:length(flds)
       img_bkgnd.(flds{i}) = inv_model.jacobian_bkgnd.(flds{i});
    end
%     img_bkgnd = data_mapper(img_bkgnd);
end
function b = has_params(s)
b = false;
if isstruct(s)
   b = any(ismember(fieldnames(s),supported_params));
end
function do_unit_test
imdl = mk_common_model('d2c2');
test = calc_jacobian_bkgnd(imdl);
unit_test_cmp('t1:type',  test.type, 'image');
unit_test_cmp('t1:elem_data',  test.elem_data, ones(1024,1));
imdl.jacobian_bkgnd = rmfield(imdl.jacobian_bkgnd,'value');
imdl.jacobian_bkgnd.node_data  = 5;
test = calc_jacobian_bkgnd(imdl);
unit_test_cmp('t2:type',  test.type, 'image');
unit_test_cmp('t2:node_data',  test.node_data, 5);
imdl.jacobian_bkgnd = rmfield(imdl.jacobian_bkgnd,'node_data');
imdl.jacobian_bkgnd.node_data.val1  = 5;
imdl.jacobian_bkgnd.node_data.val2  = ones(length(imdl.fwd_model.nodes),1);
img = calc_jacobian_bkgnd(imdl);
unit_test_cmp('t3:node_data',  img.node_data, imdl.jacobian_bkgnd.node_data);
imdl.jacobian_bkgnd = rmfield(imdl.jacobian_bkgnd,'node_data');
imdl.jacobian_bkgnd.elem_data.val1  = 5;
imdl.jacobian_bkgnd.elem_data.val2  = ones(length(imdl.fwd_model.elems),1);
img = calc_jacobian_bkgnd(imdl);
unit_test_cmp('t4:elem_data',  img.elem_data, imdl.jacobian_bkgnd.elem_data);
imdl = rmfield(imdl,'jacobian_bkgnd');
imdl.jacobian_bkgnd.resistivity.elem_data = 3;
img = calc_jacobian_bkgnd(imdl);
expect = struct(...
    'type','image', 'name', 'background image', ...
    'fwd_model', imdl.fwd_model, 'resistivity', ...
     imdl.jacobian_bkgnd.resistivity );;
unit_test_cmp('t5:resistivity',  img, expect);