Description of calc_system_mat
Home > eidors > solvers > calc_system_mat.m
calc_system_mat
PURPOSE
CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
SYNOPSIS
function system_mat = calc_system_mat(fwd_model, img)
DESCRIPTION
 CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
    system_mat= calc_system_mat( fwd_model, image)
 OR
    system_mat= calc_system_mat( image)
 it will call the fwd_model.system_mat
 if fwd_model.system_mat is a matrix, calc_system_mat will return this
 matrix
 system_mat
   system_mat.E    is FEM system_matrix
   system_mat.perm is permutation of E  i.e. E(perm,perm)
 fwd_model is a fwd_model structure
 image     is an image structure
CROSS-REFERENCE INFORMATION
This function calls:
eidors_cache EIDORS_CACHE Control eidors caching
This function is called by:
np_calc_3d_fields NP_CALC_3D_FIELDS: J= np_calc_3d_fields(fwd_model, img)
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
eit_spice function spice = eit_spice(img, [name])
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
SOURCE CODE
function system_mat = calc_system_mat(fwd_model, img)
% CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
%
%    system_mat= calc_system_mat(fwd_model, image)
% OR
%    system_mat= calc_system_mat(image)
%
% it will call the fwd_model.system_mat
%
% if fwd_model.system_mat is a matrix, calc_system_mat will return this
% matrix
%
% system_mat
%   system_mat.E    is FEM system_matrix
%   system_mat.perm is permutation of E  i.e. E(perm,perm)
% fwd_model is a fwd_model structure
% image     is an image structure
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id: calc_system_mat.m 4832 2015-03-29 21:13:53Z bgrychtol-ipa $
%system_mat= feval(fwd_model.system_mat, fwd_model, img);return
if nargin == 1
   img= fwd_model;
else
   warning('EIDORS:DeprecatedInterface', ...
      ['Calling CALC_SYSTEM_MAT with two arguments is deprecated and will cause' ...
       ' an error in a future version. First argument ignored.']);
end
warning off EIDORS:DeprecatedInterface
fwd_model= img.fwd_model;
if isnumeric(fwd_model.system_mat)
   system_mat = fwd_model.system_mat;
else
   copt.cache_obj= {fwd_model, img.elem_data};
   copt.fstr = 'system_mat';
   try % in case it's a string
       fwd_model.system_mat = str2func(fwd_model.system_mat);
   end
   system_mat = eidors_cache(fwd_model.system_mat,{fwd_model,img},copt);
end
warning on EIDORS:DeprecatedInterface